name: Check for removed URLs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - uses: actions/setup-python@v4
      - name: Build docs
        run: |
          cd docs
          make install
          . .sphinx/venv/bin/activate
          make html
      - name: Generate current URLs list
        run: |
          find ./_build/ -name '*.html' \
          | sed 's|/_build||;s|/index.html$|/|;s|.html$||' \
          | sort > new_urls.txt
      - name: Compare URLs
        run: |
          removed=$(comm -23 current_urls.txt new_urls.txt )
          if [ -n "$removed" ]; then
            echo "The following URLs were removed:"
            echo "$removed"
            exit 1
          fi
      - name: Commit current URLs
        if: github.ref == 'refs/heads/main'
        run: |
          cp new_urls.txt current_urls.txt
          git config --global user.name 'Ubuntu Robotics Community Group'
          git config --global user.email 'ubuntu-robotics-community-group@canonical.com'
          git add current_urls.txt
          git commit -m "Automated URLs update"
          git push
